"""add profile fields preferred_role expected_salary work_experience certifications

Revision ID: 1fa07e0b34e7
Revises: ae2ae4399a6d
Create Date: 2026-03-14 10:57:32.344509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa07e0b34e7'
down_revision: Union[str, None] = 'ae2ae4399a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('preferred_role', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('expected_salary', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'certifications')
    op.drop_column('profiles', 'work_experience')
    op.drop_column('profiles', 'expected_salary')
    op.drop_column('profiles', 'preferred_role')
    # ### end Alembic commands ###
